---
- name: test
  hosts: all
  tasks:
    - name: Loopig eco test
      shell: "echo this my item: {{ item }}"
      loop:
        - one
        - two
      register: echo_results
    
    - name: result
      ansible.builtin.debug:
        msg: "{{ echo_results.stdout }}"