---
- name: addng user
  hosts: all
  become: true
  tasks:
  - name: add user
    user:
      name: devops
      groups: wheel
      password: "{{ '12345' | password_hash('sha512') }}"
      state: present